src/Entity/Advert.php
<?php

namespace App\Entity;

use App\Repository\AdvertRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=AdvertRepository::class)
 * @Vich\Uploadable
 */
class Advert
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $Price;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Brand;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $Size;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="adverts")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=AdvertLike::class, mappedBy="advert")
     */
    private $likes;

    /**
     * @ORM\ManyToOne(targetEntity=PhotoGallery::class, inversedBy="adverts")
     */
    private $gallery;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="annonce_images", fileNameProperty="image")
     * @var File
     * @Assert\Image{
     *       mimeTypes = {"image/jpeg", "image/gif", "image/png", "video/mp4", "video/quicktime", "video/avi"}
     *       mimeTypesMessage = "Wrong file type (jpg,gif,png,mp4,mov,avi)"
     *
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="adverts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;




    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;


        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }


    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function __toString()
    {
        return $this->id;
    }

    public function __construct()
    {
        $this->likes = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->Brand;
    }

    public function setBrand(string $Brand): self
    {
        $this->Brand = $Brand;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->Size;
    }

    public function setSize(string $Size): self
    {
        $this->Size = $Size;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|AdvertLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(AdvertLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setAdvert($this);
        }

        return $this;
    }

    public function removeLike(AdvertLike $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getAdvert() === $this) {
                $like->setAdvert(null);
            }
        }

        return $this;
    }

    public function getGallery(): ?PhotoGallery
    {
        return $this->gallery;
    }

    public function setGallery(?PhotoGallery $gallery): self
    {
        $this->gallery = $gallery;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function isLikedByUser( User $user) : bool {
        foreach ($this->likes as $like){
            if ($like->getUser() === $user){
                return true;
            }
        }
        return false;
    }


}

src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 * @Vich\Uploadable
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Message;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;
    /**
     * @Vich\UploadableField(mapping="annonce_images", fileNameProperty="image")
     * @var File
     * * @Assert\Image{
     *       mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/pdf"}
     *       mimeTypesMessage = "Wrong file type (jpg,gif,png,mp4,mov,avi)"
     */
    private $imageFile;



    public function setImageFile(File $image = null)
    {
    $this->imageFile = $image;


    // VERY IMPORTANT:
    // It is required that at least one field changes if you are using Doctrine,
    // otherwise the event listeners won't be called and the file is lost
    if ($image) {
        // if 'updatedAt' is not defined in your entity, use another property
        $this->updatedAt = new \DateTime('now');
    }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

}

templates/pages/_filter.html.twig
{% if form is defined %}
    {{ form_start(form) }}

    {{ form_row(form.q) }}
    <h3 style="margin-bottom: 20px;margin-left: 55px">Catégories</h3>
    {{ form_row(form.categories) }}


    <button type="submit" class=" w-100 btn-color">Filtre</button>
    <button class="btn-color" href="{{ path('category') }}">Revoir toutes les annonces</button>
    {{ form_end(form) }}

{% endif %}

templates/pages/account.html.twig
{% extends "layouts/zay.html.twig" %}
{% block content %}
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto px-0">
                <div id="sidebar" class="collapse collapse-horizontal show border-end">
                    <div id="sidebar-nav" class="list-group border-0 rounded-0 text-sm-start min-vh-100">
                        <p class="mail-2 list-group-item border-end-0 d-inline-block text-truncate"> Annonces </p>

                    </div>
                </div>
            </div>
            <main class="col ps-md-2 pt-2">

                <div class="page-header pt-3">
                    <h2>{{ app.user.username }}</h2>
                    <p class="mail-2">{{ app.user.email }}</p>


                <div>
                <hr>
                <div class="row">
                    <div class="col-12">
                        <h3>Mes annonces</h3>
                        <div class="col-lg-9">
                            <div class="row">
                                {% for advert in adverts%}
                                    <div class="col-md-4">
                                        <div class="card mb-4 product-wap rounded-0">
                                            <div class="card rounded-0">
                                                <img class="card-img rounded-0 img-fluid" src="{{vich_uploader_asset(advert, 'imageFile')  }}">
                                                <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                                    <ul class="list-unstyled">

                                                        <li><a class="btn btn-success text-white mt-2" href="{{ path('advert',{'id' : advert.id}) }}"><i class="far fa-eye"></i></a></li>

                                                    </ul>
                                                </div>
                                            </div>

                                            <div class="card-body">
                                                <a class="h3 text-decoration-none text-center mb-0">{{ advert.title }}</a>
                                                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                                    <li>{{ advert.size }}</li>
                                                    <li class="pt-2">
                                                        <span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>
                                                        <span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>
                                                        <span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>
                                                        <span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>
                                                        <span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>
                                                    </li>
                                                </ul>
                                                <p>{{ advert.category.name }}</p>

                                                <p class="text-center mb-0">{{ advert.price }}€</p>
                                                <br>


                                                <span class="js-label"><a class="like text-decoration-none" href="">Likes</a></span>
                                                <span class="js-likes">{{ advert.likes | length}}</span>

                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>

                        </div>
                    </div>
                </div>
                </div>
                </div>
            </main>
        </div>
    </div>
{% endblock %}

templates/pages/category.html.twig
{% extends 'layouts/zay.html.twig' %}
{% block content %}

    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>



    <!-- Start Content -->
    <div class="container py-5">
        <div class="row">

            <div class="col-lg-3">
                <h1 class="h2 pb-4">Filtrez vos recherches</h1>
                {% if form is defined %}
                {% include 'pages/_filter.html.twig'with {form: form} only %}
                {% endif %}
                <!-- <h1 class="h2 pb-4">Filtrez vos recherches</h1>
                <ul class="list-unstyled templatemo-accordion">
                    <li class="pb-3">
                        <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
                            Semelle
                            <i class="fa fa-fw fa-chevron-circle-down mt-1"></i>
                        </a>
                        <ul id="collapseOne" class="collapse list-unstyled pl-3">
                            <li><a class="text-decoration-none" href="">Multi</a></li>
                            <li><a class="text-decoration-none" href="">Crampons</a></li>
                            <li><a class="text-decoration-none" href="">Indoor</a></li>
                            <li><a class="text-decoration-none" href="">Synthétique</a></li>

                        </ul>
                    </li>
                    <h2><a class="h2 pb-4 text-decoration-none" href="{}">Revoir tout les annonces</a></h2>
                </ul>
-->
            </div>

            <div class="col-lg-9">
                <div class="row">
                    {% for advert in adverts%}
                    <div class="col-md-4">
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card rounded-0">
                                <img class="card-img rounded-0 img-fluid" src="{{vich_uploader_asset(advert, 'imageFile')  }}">
                                <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                    <ul class="list-unstyled">

                                        <li><a class="btn btn-success text-white mt-2" href="{{ path('advert',{'id' : advert.id}) }}"><i class="far fa-eye"></i></a></li>

                                    </ul>
                                </div>
                            </div>

                            <div class="card-body">
                                <a class="h3 text-decoration-none text-center mb-0">{{ advert.title }}</a>
                                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                    <li>{{ advert.size }}</li>
                                    <li class="pt-2">
                                        <span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>
                                    </li>
                                </ul>
                                <p>{{ advert.category.name }}</p>

                                <p class="text-center mb-0">{{ advert.price }}€</p>
                                <br>


                                    <span class="js-label"><a class="like text-decoration-none" href="">Likes</a></span>
                                    <span class="js-likes">{{ advert.likes | length}}</span>

                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>

            </div>

        </div>


    </div>
    <div class="d-flex justify-content-center text-modify">
        {{ knp_pagination_render(adverts,'/pagination/pagination.html.twig') }}

</div>
    <!-- End Content -->>

    <!-- Start Brands -->
    <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Nos marques</h1>
                    <p>
                        Toutes les marques ci-dessous, sont celles disponibles sur notre site.
                    </p>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#multi-item-example" role="button" data-bs-slide="prev">
                                <i class="text-light fas fa-chevron-left"></i>
                            </a>
                        </div>
                        <!--End Controls-->

                        <!--Carousel Wrapper-->
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="multi-item-example" data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">

                                    <!--First slide-->
                                    <div class="carousel-item active brands">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{{ asset('img/580b57fcd9996e24bc43c4f8.png') }}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{{ asset('img/brand_02.png') }}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{{ asset('img/brand_03.png') }}" alt="Brand Logo"></a>
                                            </div>

                                        </div>
                                    </div>
                                    <!--End First slide-->

                                    <!--Second slide-->
                                    <div class="carousel-item brands">
                                        <div class="row">
                                            <div class="col-3 p-md-5 umbro" >
                                                <a href="#"><img class="img-fluid brand-img" src="{{ asset('img/umbro-logo.png') }}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{{ asset('img/Joma-logo.png') }}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{{ asset('img/New_Balance_logo.svg.png') }}" alt="Brand Logo"></a>
                                            </div>

                                        </div>
                                    </div>
                                    <!--End Second slide-->


                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->

                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#multi-item-example" role="button" data-bs-slide="next">
                                <i class="text-light fas fa-chevron-right"></i>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Brands-->


{% endblock %}

templates/pages/contact.html.twig
{% extends "layouts/zay.html.twig" %}
{% block content %}
    <div class="container-fluid bg-light py-5">
        <div class="col-md-6 m-auto text-center">
            <h1 class="h1">Formulaire de contact</h1>
            <p>
                Dans le cas où vous auriez un quelconque problème, question, n’hésitez pas à me contacter, je serai ravis d’en discuter avec vous.
            </p>
        </div>
    </div>

    <!-- Start Map -->
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2531.7193459974133!2d5.5052039156865655!3d50.61375238346572!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c0f96c8071fb01%3A0x7fe3d7231307b1e6!2sIPEPS%20Seraing%20Sup%C3%A9rieur!5e0!3m2!1sfr!2sbe!4v1634560101658!5m2!1sfr!2sbe" width="100%" height="450" ></iframe>
    <script>
        var mymap = L.map('mapid').setView([-23.013104, -43.394365, 13], 13);

        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            maxZoom: 18,
            attribution: 'Zay Telmplte | Template Design by <a href="https://templatemo.com/">Templatemo</a> | Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1
        }).addTo(mymap);

        L.marker([-23.013104, -43.394365, 13]).addTo(mymap)
            .bindPopup("<b>Zay</b> eCommerce Template<br />Location.").openPopup();

        mymap.scrollWheelZoom.disable();
        mymap.touchZoom.disable();
    </script>
    <!-- Ena Map -->

    <!-- Start Contact -->
    <div class="container py-5">
        <div class="row py-5">

            {{ form_start(formulaire)}}

                {{ form_row(formulaire.username,{'label':'Nom d\'utilisateur','attr' :{'placeholder':'Nom d\'utilisateur'}}) }}
                {{ form_row(formulaire.Email,{'label':'Mail','attr' :{'placeholder':'Adresse mail valide'}}) }}
            {{ form_row(formulaire.Message,{'label':'Votre message','attr' :{'placeholder':'Toutes les infos nécessaires'}}) }}
                {{ form_end(formulaire) }}



        </div>
    </div>
{% endblock %}

templates/pages/product.html.twig
{% extends 'layouts/zay.html.twig' %}

{% block content %}


    <!-- Modal -->




    <!-- Open Content -->
    <section class="bg-light">
        <div class="container pb-5">
            <div class="row">

                <div class="col-lg-5 mt-5">
                    <div class="card mb-3">
                        <img class="card-img img-fluid" src="{{asset("img/couverture/"~advert.image)  }}" alt="Card image cap" id="product-detail">
                    </div>
                    <a href="{{ path('category') }}" class="btn btn-retour btn-success btn-lg" >Retour en arrière</a>
                    <div class="row">
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="prev">


                            </a>
                        </div>
                        <!--End Controls-->
                        <!--Start Carousel Wrapper-->
                        <div id="multi-item-example" class="col-10 carousel slide carousel-multi-item" data-bs-ride="carousel">
                            <!--Start Slides-->
                            <div class="carousel-inner product-links-wap" role="listbox">




                            </div>
                          <!--  End Slides-->
                        </div>
                        <!--End Carousel Wrapper-->
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="next">

                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                </div>
                <!-- col end -->
                <div class="col-lg-7 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h2">{{ advert.title }}</h1>
                            <p class="h3 py-2">Prix: {{ advert.price }}€</p>

                            <span class="list-inline-item text-dark">Taille:  {{ advert.size }}</span>

                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <h6>Marque: </h6>
                                </li>
                                <li class="list-inline-item">
                                    <p class="text-muted"><strong>{{ advert.brand }}</strong></p>
                                </li>
                            </ul>

                            <h6>Description:</h6>
                            <br>
                            <p>{{ advert.description }}</p>
                            <br>

                                <div class="row pb-3">
                                    <div class="col d-grid">

                                        <span class="js-likes">{{ advert.likes | length}}</span><p class="like text-decoration-none" >Likes</p>
                                        {% if app.user == false %}
                                        {% elseif app.user and advert.iSLikedByUser(app.user) == false %}
                                        <a href="{{ path('like', {'id':advert.id}) }}" class="js-like-link">
                                            <i class="far fa-thumbs-up"></i>
                                        </a>

                                        {% else %}
                                        <a href="{{ path('like', {'id':advert.id}) }}" class="js-like-link">
                                            <i class="fas fa-thumbs-up"></i>
                                        </a>

                                        {% endif %}
                                         <!--    <button type="submit" class=" w-100 btn-color">Like</button> -->

                                       <!-- <button type="submit" class="btn btn-success btn-lg" name="submit" value="buy">Contacter le vendeur</button> -->
                                    </div>
                                </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}